---
name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  bump_tag:
    name: bump tag
    runs-on: ubuntu-latest
    steps:
      - name: Determine next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          patchAll: true

      - name: Push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver.outputs.nextStrict }}

  provision_canary:
    name: Provision canary
    runs-on: ubuntu-latest
    steps:
      - name: Provision canary
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.NUON_BOT_GITHUB_TOKEN }}
          repository: powertoolsdev/mono
          event-type: provision_canary
          client-payload: '{"sandbox_mode": false}'
